services:
  #  nginx-pixelfed:
  #  mysql-pixelfed:
  #  redis-pixelfed:
  php-fpm-pixelfed:
    image: ${PHPFDM_IMAGE_NAME}
    build:
      context: ./data/dockerfiles/phpfpm/.
      dockerfile: Dockerfile
    restart: unless-stopped

  mariadb-pixelfed:
    image: ${MARIADB_IMAGE_NAME}
    restart: unless-stopped

#  redis-pixelfed:
#    image:
