services:
  nginx-pixelfed:
    image: ${NGINX_IMAGE_NAME}
    build:
      context: ./data/dockerfiles/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx/ssl:/etc/nginx/ssl
      - ./data/pixelfed:/var/www/pixelfed
    depends_on:
      - php-fpm-pixelfed
    restart: unless-stopped

  php-fpm-pixelfed:
    image: ${PHPFDM_IMAGE_NAME}
    build:
      context: ./data/dockerfiles/phpfpm
      dockerfile: Dockerfile
    volumes:
      - ./data/pixelfed:/var/www/pixelfed
    environment:
      - DB_HOST=mariadb-pixelfed
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=redis-pixelfed
      - REDIS_PORT=6379
      - APP_URL=${APP_URL}
      - APP_ENV=${APP_ENV}
      - APP_DEBUG=${APP_DEBUG}
      - APP_KEY=${APP_KEY}
    depends_on:
      - mariadb-pixelfed
      - redis-pixelfed
    restart: unless-stopped

  mariadb-pixelfed:
    image: ${MARIADB_IMAGE_NAME}
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - ./data/mariadb:/var/lib/mysql
    restart: unless-stopped

  redis-pixelfed:
    image: ${REDIS_IMAGE_NAME}
    build:
      context: ./data/dockerfiles/redis
      dockerfile: Dockerfile
    volumes:
      - ./data/redis:/data
    restart: unless-stopped
